CREATE TABLE PESSOAS (
    HANDLE INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(255) NOT NULL, 
    TIPO CHAR(1) NOT NULL CHECK (TIPO IN (1, 2)), 
    CNPJCPF VARCHAR(255) NOT NULL,  
    LOGRADOURO VARCHAR(255),
    BAIRRO VARCHAR(255),
    COMPLEMENTO VARCHAR(255),
    PAIS VARCHAR(255) NOT NULL,  
    ESTADO VARCHAR(255),
    MUNICIPIO VARCHAR(255),
    EMAIL VARCHAR(255),
    NASCIMENTO DATE,
    IDENTIDADE VARCHAR(255),
    EHCLIENTE CHAR(1) NOT NULL CHECK (EHCLIENTE IN ('S', 'N')),  
    CEP VARCHAR(255),
    EHFORNECEDOR CHAR(1) NOT NULL CHECK (EHFORNECEDOR IN ('S', 'N'))  
);

CREATE TABLE USUARIOS (
    HANDLE INT PRIMARY KEY IDENTITY(1,1),
    APELIDO VARCHAR(255) NOT NULL,  
    NOME VARCHAR(255) NOT NULL,  
    EMAIL VARCHAR(255) NOT NULL  
);

CREATE TABLE CENTROSCUSTO (
    HANDLE INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(255) NOT NULL,  
    SALDO DECIMAL(18,2)
);

CREATE TABLE LOGS (
    HANDLE INT PRIMARY KEY IDENTITY(1,1),
    DATAHORA DATETIME NOT NULL,  
    TABELA VARCHAR(255),
    SERVICO CHAR(1) NOT NULL CHECK (SERVICO IN ('E','A','D')),   -- 'E' PARA ENTRADA, 'A' PARA ALTERACAO, 'D' PARA DELETAR
    REGISTRO VARCHAR(255),
    USUARIO VARCHAR(255) NOT NULL,  
    HOST VARCHAR(255)
);

CREATE TABLE FORMASPAGAMENTOS (
    HANDLE INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(255) NOT NULL  
);

CREATE TABLE BANCOCONTAS (
    HANDLE INT PRIMARY KEY IDENTITY(1,1),
    NUMEROCONTA VARCHAR(255) NOT NULL,  
    BANCO VARCHAR(255) NOT NULL,  
    AGENCIA VARCHAR(255),
    DIGITOAGENCIA VARCHAR(255),
    DIGITOCONTA VARCHAR(255),
    CHAVEPIX VARCHAR(255),
    TIPOPROPRIETARIO CHAR(1) NOT NULL CHECK (TIPOPROPRIETARIO IN ('P','T')), -- 'P' PARA PROPRIO, 'T' PARA TERCEIRO
    PESSOA INT,
    ATIVO CHAR(1) NOT NULL CHECK (ATIVO IN ('S', 'N')),  
    OBSERVACOES VARCHAR(MAX),
    FOREIGN KEY (PESSOA) REFERENCES PESSOAS(HANDLE)
);

CREATE TABLE DOCUMENTOS (
    HANDLE INT PRIMARY KEY IDENTITY(1,1),
    PESSOA INT NOT NULL,  
    DOCUMENTODIGITADO VARCHAR(255) NOT NULL, 
    DATAENTRADA DATE NOT NULL,  
    DATAEMISSAO DATE NOT NULL,  
    VALORNOMINAL DECIMAL(18,2) NOT NULL,  
    VALORESBAIXADOS DECIMAL(18,2),
    ENTRADASAIDA CHAR(1) NOT NULL CHECK (ENTRADASAIDA IN ('E', 'S')),  -- 1 PARA CADASTRADO, 2 PARA CONFIRMADO 3 PARA CANCELADO
    DATAINCLUSAO DATE,
    DATACONFIRMACAO DATE,
    USUARIOINCLUIU INT NOT NULL, 
    USUARIOCONFIRMOU INT,
    STATUS CHAR(1) NOT NULL CHECK (STATUS IN (1, 2, 3)),  
    LOG VARCHAR(MAX),
    DATAVENCIMENTO DATE,
    CENTROCUSTO INT NOT NULL,
    FOREIGN KEY (PESSOA) REFERENCES PESSOAS(HANDLE),
    FOREIGN KEY (USUARIOINCLUIU) REFERENCES USUARIOS(HANDLE),
    FOREIGN KEY (USUARIOCONFIRMOU) REFERENCES USUARIOS(HANDLE),
    FOREIGN KEY (CENTROCUSTO) REFERENCES CENTROSCUSTO(HANDLE)
);

CREATE TABLE LANCAMENTOS (
    HANDLE INT PRIMARY KEY IDENTITY(1,1),
    DATALANCAMENTO DATE NOT NULL, 
    VALORMULTA DECIMAL(18,2),
    DESCONTO DECIMAL(18,2),
    NATUREZA CHAR(1) NOT NULL CHECK (NATUREZA IN ('R', 'D')),   --'R' PARA RECEITA, 'D' PARA DESPESA
    VALOR DECIMAL(18,2) NOT NULL,  
    VALORJUROS DECIMAL(18,2),
    DOCUMENTO INT NOT NULL, 
    BANCOCONTAINTERNA INT NOT NULL,  
    BANCOCONTAPESSOA INT NOT NULL, 
    FORMAPAGAMENTO INT NOT NULL, 
    USUARIOINCLUIU INT NOT NULL, 
    FOREIGN KEY (DOCUMENTO) REFERENCES DOCUMENTOS(HANDLE),
    FOREIGN KEY (BANCOCONTAINTERNA) REFERENCES BANCOCONTAS(HANDLE),
    FOREIGN KEY (BANCOCONTAPESSOA) REFERENCES BANCOCONTAS(HANDLE),
    FOREIGN KEY (FORMAPAGAMENTO) REFERENCES FORMASPAGAMENTOS(HANDLE),
    FOREIGN KEY (USUARIOINCLUIU) REFERENCES USUARIOS(HANDLE)
);

