CREATE NONCLUSTERED INDEX IX_PESSOAS_NOME
ON PESSOAS (NOME);

CREATE NONCLUSTERED INDEX IX_PESSOAS_CNPJCPF
ON PESSOAS (CNPJCPF);

CREATE NONCLUSTERED INDEX IX_PESSOAS_EMAIL
ON PESSOAS (EMAIL);

CREATE NONCLUSTERED INDEX IX_USUARIOS_HANDLE
ON USUARIOS (HANDLE);

CREATE NONCLUSTERED INDEX IX_USUARIOS_NOME
ON USUARIOS (NOME);
